<h1> DATA PROCESSING </h1>

In [1]:
# import neccesary libraries

import numpy as np
import pandas as pd

In [2]:
# open the dataset

data = pd.read_csv('sample_dataset.csv')
data

#to decide which is dependent variable and which is not 

serialize      name    country   age   salary  purchased
0           1      John        USA  23.0  50000.0       True
1           2     Alice         UK  29.0      NaN      False
2           3       Bob     Canada  35.0  60000.0       True
3           4      Emma    Germany   NaN  75000.0       True
4           5   Michael  Australia  42.0      NaN      False
5           6     Sarah     France  31.0  58000.0       True
6           7     David        USA   NaN  62000.0      False
7           8    Olivia         UK  28.0      NaN       True
8           9     James     Canada  36.0  69000.0      False
9          10    Sophia    Germany   NaN  72000.0       True
10         11    Daniel  Australia  30.0      NaN       True
11         12       Ava     France  27.0  64000.0      False
12         13   Matthew        USA   NaN  53000.0       True
13         14       Mia         UK  40.0      NaN      False
14         15     Ethan     Canada  22.0  67000.0       True
15         16  Isabella    Germany  33.0  71000.0       True
16         17     Henry  Australia   NaN      NaN      False
17         18     Emily     France  39.0  66000.0       True
18         19     Lucas        USA  24.0  54000.0      False
19         20     Grace         UK   NaN  62000.0       True

In [3]:
# inependent variables
x = data[['name', 'country','age','salary']].values

x

array([['John', 'USA', 23.0, 50000.0],
       ['Alice', 'UK', 29.0, nan],
       ['Bob', 'Canada', 35.0, 60000.0],
       ['Emma', 'Germany', nan, 75000.0],
       ['Michael', 'Australia', 42.0, nan],
       ['Sarah', 'France', 31.0, 58000.0],
       ['David', 'USA', nan, 62000.0],
       ['Olivia', 'UK', 28.0, nan],
       ['James', 'Canada', 36.0, 69000.0],
       ['Sophia', 'Germany', nan, 72000.0],
       ['Daniel', 'Australia', 30.0, nan],
       ['Ava', 'France', 27.0, 64000.0],
       ['Matthew', 'USA', nan, 53000.0],
       ['Mia', 'UK', 40.0, nan],
       ['Ethan', 'Canada', 22.0, 67000.0],
       ['Isabella', 'Germany', 33.0, 71000.0],
       ['Henry', 'Australia', nan, nan],
       ['Emily', 'France', 39.0, 66000.0],
       ['Lucas', 'USA', 24.0, 54000.0],
       ['Grace', 'UK', nan, 62000.0]], dtype=object)

In [4]:
# dependant variable 
y = data[['purchased']].values
y

array([[ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True]])

In [5]:
# TO fill the missing data in the dataset
from sklearn.impute import SimpleImputer


In [6]:
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer = imputer.fit(x[:,2:4])
x[:,2:4]= imputer.transform(x[:,2:4])
x

array([['John', 'USA', 23.0, 50000.0],
       ['Alice', 'UK', 29.0, 63071.42857142857],
       ['Bob', 'Canada', 35.0, 60000.0],
       ['Emma', 'Germany', 31.357142857142858, 75000.0],
       ['Michael', 'Australia', 42.0, 63071.42857142857],
       ['Sarah', 'France', 31.0, 58000.0],
       ['David', 'USA', 31.357142857142858, 62000.0],
       ['Olivia', 'UK', 28.0, 63071.42857142857],
       ['James', 'Canada', 36.0, 69000.0],
       ['Sophia', 'Germany', 31.357142857142858, 72000.0],
       ['Daniel', 'Australia', 30.0, 63071.42857142857],
       ['Ava', 'France', 27.0, 64000.0],
       ['Matthew', 'USA', 31.357142857142858, 53000.0],
       ['Mia', 'UK', 40.0, 63071.42857142857],
       ['Ethan', 'Canada', 22.0, 67000.0],
       ['Isabella', 'Germany', 33.0, 71000.0],
       ['Henry', 'Australia', 31.357142857142858, 63071.42857142857],
       ['Emily', 'France', 39.0, 66000.0],
       ['Lucas', 'USA', 24.0, 54000.0],
       ['Grace', 'UK', 31.357142857142858, 62000.0]], dtype=obj

In [7]:
# many algorithms only wirks on numerics so need to onvert name to numeric
from sklearn.preprocessing import LabelEncoder


In [8]:
label_encoder_x = LabelEncoder()
x[:,1] = label_encoder_x.fit_transform(x[:,1])
x

array([['John', 5, 23.0, 50000.0],
       ['Alice', 4, 29.0, 63071.42857142857],
       ['Bob', 1, 35.0, 60000.0],
       ['Emma', 3, 31.357142857142858, 75000.0],
       ['Michael', 0, 42.0, 63071.42857142857],
       ['Sarah', 2, 31.0, 58000.0],
       ['David', 5, 31.357142857142858, 62000.0],
       ['Olivia', 4, 28.0, 63071.42857142857],
       ['James', 1, 36.0, 69000.0],
       ['Sophia', 3, 31.357142857142858, 72000.0],
       ['Daniel', 0, 30.0, 63071.42857142857],
       ['Ava', 2, 27.0, 64000.0],
       ['Matthew', 5, 31.357142857142858, 53000.0],
       ['Mia', 4, 40.0, 63071.42857142857],
       ['Ethan', 1, 22.0, 67000.0],
       ['Isabella', 3, 33.0, 71000.0],
       ['Henry', 0, 31.357142857142858, 63071.42857142857],
       ['Emily', 2, 39.0, 66000.0],
       ['Lucas', 5, 24.0, 54000.0],
       ['Grace', 4, 31.357142857142858, 62000.0]], dtype=object)

In [9]:
# Now to make a perfect dummy of particular data set 
from sklearn.preprocessing import OneHotEncoder         

In [10]:
oneHotEncoder = OneHotEncoder()
x = oneHotEncoder.fit_transform(data.country.values.reshape(-1,1)).toarray()
x

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.]])

In [11]:
label_encoder_y = LabelEncoder()
y = label_encoder_y.fit_transform(y)
y

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1],
      dtype=int64)

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.3, random_state = 0)


In [14]:
x_train

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
x_test

array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [16]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1], dtype=int64)

In [17]:
y_test

array([0, 0, 1, 0, 1, 1], dtype=int64)

In [18]:
# to make all features same 
from sklearn.preprocessing import StandardScaler


In [19]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_train

array([[-0.40824829, -0.40824829, -0.40824829, -0.52223297, -0.40824829,
         1.91485422],
       [-0.40824829, -0.40824829, -0.40824829, -0.52223297,  2.44948974,
        -0.52223297],
       [ 2.44948974, -0.40824829, -0.40824829, -0.52223297, -0.40824829,
        -0.52223297],
       [-0.40824829,  2.44948974, -0.40824829, -0.52223297, -0.40824829,
        -0.52223297],
       [-0.40824829, -0.40824829,  2.44948974, -0.52223297, -0.40824829,
        -0.52223297],
       [-0.40824829,  2.44948974, -0.40824829, -0.52223297, -0.40824829,
        -0.52223297],
       [-0.40824829, -0.40824829, -0.40824829,  1.91485422, -0.40824829,
        -0.52223297],
       [-0.40824829, -0.40824829, -0.40824829, -0.52223297,  2.44948974,
        -0.52223297],
       [ 2.44948974, -0.40824829, -0.40824829, -0.52223297, -0.40824829,
        -0.52223297],
       [-0.40824829, -0.40824829,  2.44948974, -0.52223297, -0.40824829,
        -0.52223297],
       [-0.40824829, -0.40824829, -0.40824829,  1.

In [20]:
x_test = sc_x.fit_transform(x_test)
x_test

array([[-0.4472136 , -0.4472136 , -0.4472136 ,  0.        , -0.70710678,
         2.23606798],
       [-0.4472136 , -0.4472136 , -0.4472136 ,  0.        ,  1.41421356,
        -0.4472136 ],
       [-0.4472136 , -0.4472136 , -0.4472136 ,  0.        ,  1.41421356,
        -0.4472136 ],
       [-0.4472136 ,  2.23606798, -0.4472136 ,  0.        , -0.70710678,
        -0.4472136 ],
       [ 2.23606798, -0.4472136 , -0.4472136 ,  0.        , -0.70710678,
        -0.4472136 ],
       [-0.4472136 , -0.4472136 ,  2.23606798,  0.        , -0.70710678,
        -0.4472136 ]])