In [77]:
import numpy as np 
import pandas as pd     

In [78]:
data = pd.read_csv('CrimesOnWomenData.csv')
data

Unnamed: 0              State  Year  Rape   K&A   DD   AoW   AoM    DV  \
0             0     ANDHRA PRADESH  2001   871   765  420  3544  2271  5791   
1             1  ARUNACHAL PRADESH  2001    33    55    0    78     3    11   
2             2              ASSAM  2001   817  1070   59   850     4  1248   
3             3              BIHAR  2001   888   518  859   562    21  1558   
4             4       CHHATTISGARH  2001   959   171   70  1763   161   840   
..          ...                ...   ...   ...   ...  ...   ...   ...   ...   
731         731         D&N Haveli  2021  1250  4083  141  2068   417  4731   
732         732        Daman & Diu  2021   315   904   16  1851    10   501   
733         733           Delhi UT  2021     2     1    0     5     1     9   
734         734        Lakshadweep  2021     0     0    0     1     1     3   
735         735         Puducherry  2021     2     0    2    31     3    12   

     WT  
0     7  
1     0  
2     0  
3    83  
4     0  
..   ..  
731   4  
732   1  
733   0  
734   0  
735   0  

[736 rows x 10 columns]

In [79]:
# independent variables 
x = data[['Year','Rape', 'K&A','DD','AoM','DV','WT']].values
x

array([[2001,  871,  765, ..., 2271, 5791,    7],
       [2001,   33,   55, ...,    3,   11,    0],
       [2001,  817, 1070, ...,    4, 1248,    0],
       ...,
       [2021,    2,    1, ...,    1,    9,    0],
       [2021,    0,    0, ...,    1,    3,    0],
       [2021,    2,    0, ...,    3,   12,    0]], dtype=int64)

In [80]:
# dependent varaibles 
y = data[['State']].values
y

array([['ANDHRA PRADESH'],
       ['ARUNACHAL PRADESH'],
       ['ASSAM'],
       ['BIHAR'],
       ['CHHATTISGARH'],
       ['GOA'],
       ['GUJARAT'],
       ['HARYANA'],
       ['HIMACHAL PRADESH'],
       ['JAMMU & KASHMIR'],
       ['JHARKHAND'],
       ['KARNATAKA'],
       ['KERALA'],
       ['MADHYA PRADESH'],
       ['MAHARASHTRA'],
       ['MANIPUR'],
       ['MEGHALAYA'],
       ['MIZORAM'],
       ['NAGALAND'],
       ['ODISHA'],
       ['PUNJAB'],
       ['RAJASTHAN'],
       ['SIKKIM'],
       ['TAMIL NADU'],
       ['TRIPURA'],
       ['UTTAR PRADESH'],
       ['UTTARAKHAND'],
       ['WEST BENGAL'],
       ['A & N ISLANDS'],
       ['CHANDIGARH'],
       ['D & N HAVELI'],
       ['DAMAN & DIU'],
       ['LAKSHADWEEP'],
       ['PUDUCHERRY'],
       ['ANDHRA PRADESH'],
       ['ARUNACHAL PRADESH'],
       ['ASSAM'],
       ['BIHAR'],
       ['CHHATTISGARH'],
       ['GOA'],
       ['GUJARAT'],
       ['HARYANA'],
       ['HIMACHAL PRADESH'],
       ['JAMMU & KASHMIR'],


In [81]:
from sklearn.impute import SimpleImputer

In [82]:
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer = imputer.fit(x[:,2:4])
x[:,2:4]= imputer.transform(x[:,2:4])
x

array([[2001,  871,  765, ..., 2271, 5791,    7],
       [2001,   33,   55, ...,    3,   11,    0],
       [2001,  817, 1070, ...,    4, 1248,    0],
       ...,
       [2021,    2,    1, ...,    1,    9,    0],
       [2021,    0,    0, ...,    1,    3,    0],
       [2021,    2,    0, ...,    3,   12,    0]], dtype=int64)

In [83]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [84]:
label_encoder_y = LabelEncoder()
y = label_encoder_y.fit_transform(y)
y

c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([ 2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55, 57, 59, 60, 64, 65, 68,  0, 10, 14, 16, 35, 51,
        2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55, 57, 59, 60, 64, 65, 68,  0, 10, 14, 16, 35, 51,
        2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55, 57, 59, 60, 64, 65, 68,  0, 10, 14, 16, 35, 51,
        2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55, 57, 59, 60, 64, 65, 68,  0, 10, 14, 16, 35, 51,
        2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55, 57, 59, 60, 64, 65, 68,  0, 10, 14, 16, 35, 51,
        2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55, 57, 59, 60, 64, 65, 68,  0, 10, 14, 16, 35, 51,
        2,  3,  4,  8, 11, 19, 20, 23, 24, 27, 28, 31, 32, 37, 38, 39, 40,
       41, 47, 49, 52, 55

In [85]:
oneHotEncoder = OneHotEncoder()
y = oneHotEncoder.fit_transform(data.State.values.reshape(-1,1)).toarray()
y

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [86]:
from sklearn.model_selection import train_test_split


In [87]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [88]:
x_train

array([[ 2019,   730,  9025, ...,    11,  2397,    40],
       [ 2001,   562,    97, ...,    81,  2561,     0],
       [ 2005,  1217,  2256, ...,  2881,  4505,     0],
       ...,
       [ 2019,    63,    68, ...,     6,    54,     0],
       [ 2017,   605,  6182, ...,     1,  3776,    24],
       [ 2020,  5310,  4739, ...,    85, 13765,    67]], dtype=int64)

In [89]:
x_test

array([[2006,  147,  183, ...,  113,  358,    0],
       [2006,   72,    1, ...,    0,    1,    0],
       [2001, 1302,  611, ..., 1120, 6090,    1],
       ...,
       [2012,  706, 2160, ...,  208, 1985,   24],
       [2006,    6,   14, ...,    1,    5,    0],
       [2007,    1,    0, ...,    0,    2,    0]], dtype=int64)

In [90]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [91]:
y_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [92]:
from sklearn.preprocessing import StandardScaler

In [93]:
sc_x = StandardScaler()

In [94]:
x_train = sc_x.fit_transform(x_train)
x_train

array([[ 1.29629157e+00,  3.27188086e-03,  3.99059798e+00, ...,
        -3.90952898e-01, -4.78996508e-02,  1.22939178e-01],
       [-1.65112635e+00, -1.70292271e-01, -5.19810578e-01, ...,
        -3.09431827e-01, -7.66809780e-03, -3.76183224e-01],
       [-9.96144589e-01,  5.06401298e-01,  5.70912101e-01, ...,
         2.95141104e+00,  4.69222994e-01, -3.76183224e-01],
       ...,
       [ 1.29629157e+00, -6.85819128e-01, -5.34461323e-01, ...,
        -3.96775832e-01, -6.22671167e-01, -3.76183224e-01],
       [ 9.68800690e-01, -1.25868113e-01,  2.55431981e+00, ...,
        -4.02598765e-01,  2.90388834e-01, -7.67097828e-02],
       [ 1.46003701e+00,  4.73496127e+00,  1.82531896e+00, ...,
        -3.04773480e-01,  2.74083385e+00,  4.59846799e-01]])

In [95]:
x_test = sc_x.fit_transform(x_test)
x_test

array([[-0.8973456 , -0.58575856, -0.48065408, ..., -0.28182485,
        -0.56782078, -0.32087755],
       [-0.8973456 , -0.66108245, -0.57068789, ..., -0.45198955,
        -0.65816994, -0.32087755],
       [-1.74339243,  0.57422935, -0.26892624, ...,  1.23459862,
         0.88282724, -0.30828182],
       ...,
       [ 0.1179106 , -0.0243445 ,  0.49735047, ..., -0.13876603,
        -0.15606148, -0.01858012],
       [-0.8973456 , -0.72736748, -0.5642569 , ..., -0.45048366,
        -0.65715762, -0.32087755],
       [-0.72813623, -0.73238907, -0.57118258, ..., -0.45198955,
        -0.65791686, -0.32087755]])